vm_root_password: 'password'
ssh_key: ansible_ed25519
base_image_url_7: https://cloud.centos.org/centos/7/images
base_image_name_7: CentOS-7-x86_64-GenericCloud.qcow2
base_image_url_8: https://repo.almalinux.org/almalinux/8/cloud/x86_64/images
base_image_name_8: AlmaLinux-8-GenericCloud-latest.x86_64.qcow2
base_image_url_9: https://repo.almalinux.org/almalinux/9/cloud/x86_64/images
base_image_name_9: AlmaLinux-9-GenericCloud-latest.x86_64.qcow2
base_image_url_r9: https://dl.rockylinux.org/pub/rocky/9/images/x86_64
base_image_name_r9: Rocky-9-GenericCloud.latest.x86_64.qcow2
base_image_url_sles: https://download.opensuse.org/repositories/Cloud%3A/Images%3A/Leap_15.6/images
base_image_name_sles: openSUSE-Leap-15.6.x86_64-NoCloud.qcow2

virtual_machines:
  - {
    name: 'cnx-ns',
    cpu: 2,
    mem: 2,
    hdd1: 20,
    ip: '10.0.22.2',
    base_image: "{{ __base_image_name_9 }}"
  }
  - {
    name: 'cnx-ds',
    cpu: 2,
    mem: 2,
    hdd1: 20,
    ip: '10.0.22.4',
    base_image: "{{ __base_image_name_9 }}"
  }
  - {
    name: 'cnx-keycloak',
    cpu: 2,
    mem: 2,
    hdd1: 20,
    ip: '10.0.22.5',
    base_image: "{{ __base_image_name_9 }}"
  }
  - {
    name: 'cnx8-db2-was',
    cpu: 6,
    mem: 16,
    hdd1: 100,
    ip: '10.0.22.90',
    base_image: "{{ __base_image_name_9 }}"
  }
  - {
    name: 'cnx8-db2-db',
    cpu: 4,
    mem: 8,
    hdd1: 100,
    ip: '10.0.22.91',
    base_image: "{{ __base_image_name_9 }}"
  }
  - {
    name: 'cnx8-db2',
    cpu: 2,
    mem: 2,
    hdd1: 40,
    ip: '10.0.22.92',
    base_image: "{{ __base_image_name_9 }}"
  }
  - {
    name: 'cnx8-db2-nfs',
    cpu: 2,
    mem: 2,
    hdd1: 200,
    ip: '10.0.22.93',
    base_image: "{{ __base_image_name_9 }}"
  }
  - {
    name: 'cnx8-db2-cp',
    cpu: 12,
    mem: 28,
    hdd1: 120,
    ip: '10.0.22.95',
    base_image: "{{ __base_image_name_9 }}"
  }
  - {
    name: 'cnx8-was1',
    cpu: 6,
    mem: 12,
    hdd1: 100,
    ip: '10.0.22.81',
    base_image: "{{ __base_image_name_9 }}"
  }
  - {
    name: 'cnx8-was2',
    cpu: 6,
    mem: 12,
    hdd1: 100,
    ip: '10.0.22.82',
    base_image: "{{ __base_image_name_9 }}"
  }
  - {
    name: 'cnx8-db',
    cpu: 4,
    mem: 8,
    hdd1: 100,
    ip: '10.0.22.83',
    base_image: "{{ __base_image_name_9 }}"
  }
  - {
    name: 'cnx8',
    cpu: 2,
    mem: 2,
    hdd1: 40,
    ip: '10.0.22.80',
    base_image: "{{ __base_image_name_9 }}"
  }
  - {
    name: 'cnx8-nfs',
    cpu: 2,
    mem: 2,
    hdd1: 200,
    ip: '10.0.22.84',
    base_image: "{{ __base_image_name_9 }}"
  }
  - {
    name: 'cnx8-k8s-master',
    cpu: 8,
    mem: 8,
    hdd1: 120,
    ip: '10.0.22.85',
    base_image: "{{ __base_image_name_9 }}"
  }
  - {
    name: 'cnx8-k8s-worker1',
    cpu: 8,
    mem: 12,
    hdd1: 120,
    ip: '10.0.22.86',
    base_image: "{{ __base_image_name_9 }}"
  }
  - {
    name: 'cnx8-k8s-worker2',
    cpu: 8,
    mem: 12,
    hdd1: 120,
    ip: '10.0.22.87',
    base_image: "{{ __base_image_name_9 }}"
  }
  - {
    name: 'ansible',
    cpu: 2,
    mem: 2,
    hdd1: 40,
    ip: '10.0.22.110',
    base_image: "{{ __base_image_name_r9 }}"
  }
  - {
    name: 'ansible-ihs',
    cpu: 2,
    mem: 2,
    hdd1: 40,
    ip: '10.0.22.111',
    base_image: "{{ __base_image_name_r9 }}"
  }
  - {
    name: 'ansible-db',
    cpu: 4,
    mem: 8,
    hdd1: 100,
    ip: '10.0.22.112',
    base_image: "{{ __base_image_name_r9 }}"
  }
  - {
    name: 'ansible-cnx1',
    cpu: 6,
    mem: 16,
    hdd1: 100,
    ip: '10.0.22.113',
    base_image: "{{ __base_image_name_r9 }}"
  }
  - {
    name: 'ansible-viewer1',
    cpu: 4,
    mem: 12,
    hdd1: 100,
    ip: '10.0.22.115',
    base_image: "{{ __base_image_name_r9 }}"
  }
  - {
    name: 'ansible-nfs',
    cpu: 2,
    mem: 2,
    hdd1: 200,
    ip: '10.0.22.117',
    base_image: "{{ __base_image_name_r9 }}"
  }
  - {
    name: 'ansible-cp',
    cpu: 12,
    mem: 28,
    hdd1: 120,
    ip: '10.0.22.118',
    base_image: "{{ __base_image_name_r9 }}"
  }
  - {
    name: 'clt1-rh',
    cpu: 2,
    mem: 2,
    hdd1: 20,
    ip: '10.0.22.119',
    base_image: "{{ __base_image_name_r9 }}"
  }
  - {
    name: 'clt2',
    cpu: 2,
    mem: 2,
    hdd1: 20,
    ip: '10.0.22.120',
    base_image: "{{ __base_image_name_r9 }}"
  }
vm_network: 'vm_network'
