vm_root_password: 'password'
ssh_key: ansible_ed25519
base_image_url_7: https://cloud.centos.org/centos/7/images
base_image_name_7: CentOS-7-x86_64-GenericCloud.qcow2
base_image_url_8: https://repo.almalinux.org/almalinux/8/cloud/x86_64/images
base_image_name_8: AlmaLinux-8-GenericCloud-8.9-20231128.x86_64.qcow2
base_image_url_9: https://repo.almalinux.org/almalinux/9/cloud/x86_64/images
base_image_name_9: AlmaLinux-9-GenericCloud-9.3-20231113.x86_64.qcow2
base_image_url_r9: https://dl.rockylinux.org/pub/rocky/9/images
base_image_name_r9: Rocky-9-GenericCloud.latest.x86_64.qcow2
base_image_url_sles: https://download3.opensuse.org/repositories/Cloud%3A/Images%3A/Leap_15.6/images
base_image_name_sles: openSUSE-Leap-15.6.x86_64-NoCloud.qcow2

virtual_machines:
  - {
    name: 'cnx-ns',
    cpu: 2,
    mem: 2,
    hdd1: 20,
    ip: '10.0.22.2',
    base_image: "{{ __base_image_name_9 }}"
  }
  - {
    name: 'cnx-ds',
    cpu: 2,
    mem: 2,
    hdd1: 20,
    ip: '10.0.22.4',
    base_image: "{{ __base_image_name_9 }}"
  }
  - {
    name: 'cnx-keycloak',
    cpu: 2,
    mem: 4,
    hdd1: 20,
    ip: '10.0.22.5',
    base_image: "{{ __base_image_name_9 }}"
  }
  - {
    name: 'cnx8-db2-was',
    cpu: 6,
    mem: 16,
    hdd1: 100,
    ip: '10.0.22.90',
    base_image: "{{ __base_image_name_9 }}"
  }
  - {
    name: 'cnx8-db2-db',
    cpu: 4,
    mem: 8,
    hdd1: 100,
    ip: '10.0.22.91',
    base_image: "{{ __base_image_name_9 }}"
  }
  - {
    name: 'cnx8-db2',
    cpu: 2,
    mem: 2,
    hdd1: 40,
    ip: '10.0.22.92',
    base_image: "{{ __base_image_name_9 }}"
  }
  - {
    name: 'cnx8-db2-nfs',
    cpu: 2,
    mem: 2,
    hdd1: 200,
    ip: '10.0.22.93',
    base_image: "{{ __base_image_name_9 }}"
  }
  - {
    name: 'cnx8-db2-cp',
    cpu: 12,
    mem: 28,
    hdd1: 120,
    ip: '10.0.22.95',
    base_image: "{{ __base_image_name_9 }}"
  }
  - {
    name: 'cnx7',
    cpu: 2,
    mem: 2,
    hdd1: 20,
    ip: '10.0.22.100',
    base_image: "{{ __base_image_name_8 }}"
  }
  - {
    name: 'cnx7-ihs',
    cpu: 2,
    mem: 2,
    hdd1: 20,
    ip: '10.0.22.101',
    base_image: "{{ __base_image_name_8 }}"
  }
  - {
    name: 'cnx7-dmgr',
    cpu: 2,
    mem: 4,
    hdd1: 40,
    ip: '10.0.22.102',
    base_image: "{{ __base_image_name_8 }}"
  }
  - {
    name: 'cnx7-cnx1',
    cpu: 6,
    mem: 12,
    hdd1: 80,
    ip: '10.0.22.103',
    base_image: "{{ __base_image_name_8 }}"
  }
  - {
    name: 'cnx7-cnx2',
    cpu: 6,
    mem: 12,
    hdd1: 80,
    ip: '10.0.22.104',
    base_image: "{{ __base_image_name_8 }}"
  }
  - {
    name: 'cnx7-docs1',
    cpu: 4,
    mem: 8,
    hdd1: 80,
    ip: '10.0.22.105',
    base_image: "{{ __base_image_name_8 }}"
  }
  - {
    name: 'cnx7-docs2',
    cpu: 4,
    mem: 8,
    hdd1: 80,
    ip: '10.0.22.106',
    base_image: "{{ __base_image_name_8 }}"
  }
  - {
    name: 'cnx7-k8s-master',
    cpu: 4,
    mem: 8,
    hdd1: 80,
    ip: '10.0.22.107',
    base_image: "{{ __base_image_name_8 }}"
  }
  - {
    name: 'cnx7-k8s-worker1',
    cpu: 6,
    mem: 12,
    hdd1: 80,
    ip: '10.0.22.108',
    base_image: "{{ __base_image_name_8 }}"
  }
  - {
    name: 'cnx7-k8s-worker2',
    cpu: 6,
    mem: 12,
    hdd1: 80,
    ip: '10.0.22.109',
    base_image: "{{ __base_image_name_8 }}"
  }
  - {
    name: 'cnx7-db',
    cpu: 4,
    mem: 8,
    hdd1: 100,
    ip: '10.0.22.116',
    base_image: "{{ __base_image_name_9 }}"
  }
  - {
    name: 'cnx7-nfs',
    cpu: 2,
    mem: 2,
    hdd1: 200,
    ip: '10.0.22.117',
    base_image: "{{ __base_image_name_9 }}"
  }
  - {
    name: 'cnx7-sles-was',
    cpu: 6,
    mem: 16,
    hdd1: 100,
    ip: '10.0.22.76',
    base_image: "{{ __base_image_name_sles }}"
  }
  - {
    name: 'cnx7-sles-db',
    cpu: 4,
    mem: 16,
    hdd1: 100,
    ip: '10.0.22.77',
    base_image: "{{ __base_image_name_sles }}"
  }
  - {
    name: 'dx-lb',
    cpu: 2,
    mem: 2,
    hdd1: 100,
    ip: '10.0.22.50',
    base_image: "{{ __base_image_name_9 }}"
  }
  - {
    name: 'dx-k8s-master',
    cpu: 4,
    mem: 4,
    hdd1: 100,
    ip: '10.0.22.51',
    base_image: "{{ __base_image_name_9 }}"
  }
  - {
    name: 'dx-k8s-worker1',
    cpu: 4,
    mem: 16,
    hdd1: 100,
    ip: '10.0.22.52',
    base_image: "{{ __base_image_name_9 }}"
  }
  - {
    name: 'dx-k8s-worker2',
    cpu: 4,
    mem: 16,
    hdd1: 100,
    ip: '10.0.22.53',
    base_image: "{{ __base_image_name_9 }}"
  }
  - {
    name: 'dx-nfs',
    cpu: 2,
    mem: 4,
    hdd1: 200,
    ip: '10.0.22.54',
    base_image: "{{ __base_image_name_9 }}"
  }
  - {
    name: 'cnx8-nfs',
    cpu: 2,
    mem: 4,
    hdd1: 200,
    ip: '10.0.22.40',
    base_image: "{{ __base_image_name_9 }}"
  }
  - {
    name: 'cnx8-ihs',
    cpu: 2,
    mem: 4,
    hdd1: 40,
    ip: '10.0.22.41',
    base_image: "{{ __base_image_name_9 }}"
  }
  - {
    name: 'cnx8-dmgr',
    cpu: 2,
    mem: 8,
    hdd1: 100,
    ip: '10.0.22.42',
    base_image: "{{ __base_image_name_9 }}"
  }
  - {
    name: 'cnx8-cnx1',
    cpu: 8,
    mem: 16,
    hdd1: 100,
    ip: '10.0.22.43',
    base_image: "{{ __base_image_name_9 }}"
  }
  - {
    name: 'cnx8-docs1',
    cpu: 4,
    mem: 8,
    hdd1: 100,
    ip: '10.0.22.44',
    base_image: "{{ __base_image_name_9 }}"
  }
vm_network: 'vm_network'
