---
# defaults file for roles/kvm_provision
__base_image_url_7: '{{ base_image_url_7 | default("https://cloud.centos.org/centos/7/images") }}'
__base_image_name_7: '{{ base_image_name_7 | default("CentOS-7-x86_64-GenericCloud.qcow2") }}'
__base_image_url_8: '{{ base_image_url_8 | default("https://repo.almalinux.org/almalinux/8/cloud/x86_64/images") }}'
__base_image_name_8: '{{ base_image_name_8 | default("AlmaLinux-8-GenericCloud-8.9-20231128.x86_64.qcow2") }}'
__base_image_url_9: '{{ base_image_url_9 | default("https://repo.almalinux.org/almalinux/9/cloud/x86_64/images") }}'
__base_image_name_9: '{{ base_image_name_9 | default("AlmaLinux-9-GenericCloud-9.3-20231113.x86_64.qcow2") }}'
__base_image_7: "{{ __base_image_url_7 }}/{{ __base_image_name_7 }}"
__base_image_8: "{{ __base_image_url_8 }}/{{ __base_image_name_8 }}"
__base_image_9: "{{ __base_image_url_9 }}/{{ __base_image_name_9 }}"
__base_images:
  - {
      name: "{{ __base_image_name_7 }}",
      url: "{{ __base_image_url_7 }}"
    }
  - {
      name: "{{ __base_image_name_8 }}",
      url: "{{ __base_image_url_8 }}"
    }
  - {
      name: "{{ __base_image_name_9 }}",
      url: "{{ __base_image_url_9 }}"
    }
__default_packages: '{{ default_packages | default("bash-completion, vim-enhanced, curl, jq, wget, qemu-guest-agent, dnsmasq, python3") }}'
__ip_net_base: '{{ ip_net_base | default("10.0.22") }}'
__vm_net_bridge: '{{ vm_net_bridge | default("virbr1") }}'
__libvirt_pool_dir: '{{ lib_virt_pool_dir | default("/var/lib/libvirt/images") }}'
__ssh_key: '{{ ssh_key | default("iac-ed25519.pub") }}'
__user_password: '{{ user_password | default("password") }}'
__virtual_machines: '{{ virtual_machines }}'
__vm_domain: '{{ vm_domain | default("stoeps.home") }}'
__vm_network: '{{ vm_network | default("default") }}'
__root_password: '{{ root_password | default("password") }}'
__root_ssh_key: "{{ lookup('ansible.builtin.file', 'ansible_ed25519.pub' )}}"

__users:
  sysadmin:
    password: password
    ssh_key: "{{ lookup('ansible.builtin.file', 'ansible_ed25519.pub' )}}"
    shell: /usr/bin/bash
    groups: wheel
  ansible:
    password: password
    ssh_key: "{{ lookup('ansible.builtin.file', 'ansible_ed25519.pub' )}}"
    shell: /usr/bin/bash
    groups: wheel

