---
# defaults file for roles/kvm_provision
__base_image_name: '{{ base_image_name | default("Rocky-9-GenericCloud-Base.latest.x86_64.qcow2") }}'
__base_image_url: '{{ base_image_url | default("https://download.rockylinux.org/pub/rocky/9/images/x86_64") }}'
__default_packages: '{{ default_packages | default("bash-completion, vim-enhanced, curl, jq, wget, qemu-guest-agent, dnsmasq, python3"} }}'
__libvirt_pool_dir: '{{ lib_virt_pool_dir | default("/var/lib/libvirt/images") }}'
__ssh_key: '{{ ssh_key | default("iac-ed25519.pub") }}'
__user_password: '{{ user_password | default("password") }}'
__virtual_machines: '{{ virtual_machines }}'
__vm_domain: '{{ vm_domain | default("stoeps.home") }}'
__vm_network: '{{ vm_network | default("default") }}'
__vm_root_password: '{{ vm_root_password | default("password") }}'

