---
# defaults file for roles/kvm_provision
__base_image_name: '{{ base_image_name | default("Rocky-9-GenericCloud-Base.latest.x86_64.qcow2") }}'
__base_image_checksum: '{{ base_image_checksum }}'
__base_image_url: '{{ base_image_url | default("https://download.rockylinux.org/pub/rocky/9/images/x86_64") }}'
__default_packages: '{{ default_packages | default("bash-completion, vim-enhanced, curl, jq, wget, qemu-guest-agent, dnsmasq, python3") }}'
__ip_net_base: '{{ ip_net_base | default("10.0.22") }}'
__vm_net_bridge: '{{ vm_net_bridge | default("virbr1") }}'
__libvirt_pool_dir: '{{ lib_virt_pool_dir | default("/var/lib/libvirt/images") }}'
__ssh_key: '{{ ssh_key | default("iac-ed25519.pub") }}'
__user_password: '{{ user_password | default("password") }}'
__virtual_machines: '{{ virtual_machines }}'
__vm_domain: '{{ vm_domain | default("stoeps.home") }}'
__vm_network: '{{ vm_network | default("default") }}'
__root_password: '{{ root_password | default("password") }}'
__root_ssh_key: "{{ lookup('ansible.builtin.file', 'ansible_ed25519.pub' )}}"

__users:
  sysadmin:
    password: password
    ssh_key: "{{ lookup('ansible.builtin.file', 'ansible_ed25519.pub' )}}"
    shell: /usr/bin/bash
    groups: wheel
  ansible:
    password: password
    ssh_key: "{{ lookup('ansible.builtin.file', 'ansible_ed25519.pub' )}}"
    shell: /usr/bin/bash
    groups: wheel

